FROM python:3.12-slim

WORKDIR /app

COPY modbus/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install debugpy

COPY modbus/modbus_poll.py .

CMD ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "modbus_poll.py"]
