version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
      - "9003:9003"
    volumes:
      - ./php:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"

  modbus:
    build:
      context: .
      dockerfile: Dockerfile.modbus.dev
    ports:
      - "5678:5678"
    volumes:
      - ./modbus:/app

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gridsight
    ports:
      - "3306:3306"
